// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/fogo-sh/ethos/ent/schema"
	"github.com/fogo-sh/ethos/ent/tenant"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[1].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescIcon is the schema descriptor for icon field.
	tenantDescIcon := tenantFields[2].Descriptor()
	// tenant.IconValidator is a validator for the "icon" field. It is called by the builders before save.
	tenant.IconValidator = tenantDescIcon.Validators[0].(func(string) error)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantFields[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() uuid.UUID)
}
